const mock = [{
  'id': 35015575,
  'name': 'webtorrent-desktop',
  'full_name': 'feross/webtorrent-desktop',
  'owner': {
    'login': 'feross',
    'id': 121766,
    'avatar_url': 'https://avatars.githubusercontent.com/u/121766?v=3',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/feross',
    'html_url': 'https://github.com/feross',
    'followers_url': 'https://api.github.com/users/feross/followers',
    'following_url': 'https://api.github.com/users/feross/following{/other_user}',
    'gists_url': 'https://api.github.com/users/feross/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/feross/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/feross/subscriptions',
    'organizations_url': 'https://api.github.com/users/feross/orgs',
    'repos_url': 'https://api.github.com/users/feross/repos',
    'events_url': 'https://api.github.com/users/feross/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/feross/received_events',
    'type': 'User',
    'site_admin': false
  },
  'private': false,
  'html_url': 'https://github.com/feross/webtorrent-desktop',
  'description': ':heart: Streaming torrent app for Mac, Windows, and Linux (BitTorrent & WebTorrent)',
  'fork': false,
  'url': 'https://api.github.com/repos/feross/webtorrent-desktop',
  'forks_url': 'https://api.github.com/repos/feross/webtorrent-desktop/forks',
  'keys_url': 'https://api.github.com/repos/feross/webtorrent-desktop/keys{/key_id}',
  'collaborators_url': 'https://api.github.com/repos/feross/webtorrent-desktop/collaborators{/collaborator}',
  'teams_url': 'https://api.github.com/repos/feross/webtorrent-desktop/teams',
  'hooks_url': 'https://api.github.com/repos/feross/webtorrent-desktop/hooks',
  'issue_events_url': 'https://api.github.com/repos/feross/webtorrent-desktop/issues/events{/number}',
  'events_url': 'https://api.github.com/repos/feross/webtorrent-desktop/events',
  'assignees_url': 'https://api.github.com/repos/feross/webtorrent-desktop/assignees{/user}',
  'branches_url': 'https://api.github.com/repos/feross/webtorrent-desktop/branches{/branch}',
  'tags_url': 'https://api.github.com/repos/feross/webtorrent-desktop/tags',
  'blobs_url': 'https://api.github.com/repos/feross/webtorrent-desktop/git/blobs{/sha}',
  'git_tags_url': 'https://api.github.com/repos/feross/webtorrent-desktop/git/tags{/sha}',
  'git_refs_url': 'https://api.github.com/repos/feross/webtorrent-desktop/git/refs{/sha}',
  'trees_url': 'https://api.github.com/repos/feross/webtorrent-desktop/git/trees{/sha}',
  'statuses_url': 'https://api.github.com/repos/feross/webtorrent-desktop/statuses/{sha}',
  'languages_url': 'https://api.github.com/repos/feross/webtorrent-desktop/languages',
  'stargazers_url': 'https://api.github.com/repos/feross/webtorrent-desktop/stargazers',
  'contributors_url': 'https://api.github.com/repos/feross/webtorrent-desktop/contributors',
  'subscribers_url': 'https://api.github.com/repos/feross/webtorrent-desktop/subscribers',
  'subscription_url': 'https://api.github.com/repos/feross/webtorrent-desktop/subscription',
  'commits_url': 'https://api.github.com/repos/feross/webtorrent-desktop/commits{/sha}',
  'git_commits_url': 'https://api.github.com/repos/feross/webtorrent-desktop/git/commits{/sha}',
  'comments_url': 'https://api.github.com/repos/feross/webtorrent-desktop/comments{/number}',
  'issue_comment_url': 'https://api.github.com/repos/feross/webtorrent-desktop/issues/comments{/number}',
  'contents_url': 'https://api.github.com/repos/feross/webtorrent-desktop/contents/{+path}',
  'compare_url': 'https://api.github.com/repos/feross/webtorrent-desktop/compare/{base}...{head}',
  'merges_url': 'https://api.github.com/repos/feross/webtorrent-desktop/merges',
  'archive_url': 'https://api.github.com/repos/feross/webtorrent-desktop/{archive_format}{/ref}',
  'downloads_url': 'https://api.github.com/repos/feross/webtorrent-desktop/downloads',
  'issues_url': 'https://api.github.com/repos/feross/webtorrent-desktop/issues{/number}',
  'pulls_url': 'https://api.github.com/repos/feross/webtorrent-desktop/pulls{/number}',
  'milestones_url': 'https://api.github.com/repos/feross/webtorrent-desktop/milestones{/number}',
  'notifications_url': 'https://api.github.com/repos/feross/webtorrent-desktop/notifications{?since,all,participating}',
  'labels_url': 'https://api.github.com/repos/feross/webtorrent-desktop/labels{/name}',
  'releases_url': 'https://api.github.com/repos/feross/webtorrent-desktop/releases{/id}',
  'deployments_url': 'https://api.github.com/repos/feross/webtorrent-desktop/deployments',
  'created_at': '2015-05-04T05:21:35Z',
  'updated_at': '2016-08-26T23:13:33Z',
  'pushed_at': '2016-08-27T06:56:14Z',
  'git_url': 'git://github.com/feross/webtorrent-desktop.git',
  'ssh_url': 'git@github.com:feross/webtorrent-desktop.git',
  'clone_url': 'https://github.com/feross/webtorrent-desktop.git',
  'svn_url': 'https://github.com/feross/webtorrent-desktop',
  'homepage': 'https://webtorrent.io/desktop',
  'size': 10169,
  'stargazers_count': 2120,
  'watchers_count': 2120,
  'language': 'JavaScript',
  'has_issues': true,
  'has_downloads': true,
  'has_wiki': false,
  'has_pages': false,
  'forks_count': 187,
  'mirror_url': null,
  'open_issues_count': 53,
  'forks': 187,
  'open_issues': 53,
  'watchers': 2120,
  'default_branch': 'master'
}
]
module.exports = router => {
  router.get('/api/users/:id/starred', function *(next) {
    this.body = mock
    yield next
  })
}
